---
# IOS specific settings
#
device_os: ios
provider: "{{ cli }}"
cli:
  host: "{{ ios_cli_host | default(inventory_hostname) }}"
  username: "{{ ios_cli_user | default('user') }}"
  password: "{{ ios_cli_pass | default('password') }}"
  transport: cli
  authorize: yes

# NTP settings
#
ntp_source_interface: Vlan1
ntp_servers:
  - 1.1.1.1 
  - 2.2.2.2
  - 3.3.3.3
  - 4.4.4.4

# SNMP settings
#
snmp_contact: network operations
snmp_location: data center
snmp_communities:
  - { name: public, access: RO }
  - { name: private, access: RW }
  - { name: operations, access: RW }
