---
- name: configure openswitch system settings
  ops_config:
    lines:
      - hostname {{ system_hostname }}
      - domain-name {{ system_domain_name }}
    config: "{{ config }}"
    provider: "{{ provider }}"


