---
name: ensure_base_config
description: Ensure base config on remote network devices
runner_type: local-shell-cmd
entry_point: ""
enabled: true
parameters:
  sudo:
    immutable: true
    default: true
  kwarg_op:
    immutable: true
  timeout:
    default: 6000
  cmd:
    description: "Command to run"
    immutable: true
    default: "ansible-playbook /opt/stackstorm/packs/${ST2_ACTION_PACK_NAME}/playbooks/site.yaml -i /opt/stackstorm/packs/${ST2_ACTION_PACK_NAME}/playbooks/hosts --extra-vars='devices={{ devices }}'"
  devices:
    description: "Ansible hosts"
    type: string
    required: true
