---
- name: collect device facts and display OS version
  hosts: "{{ devices | default('all') }}"
  gather_facts: no
  connection: local

  roles:
    - { role: network_facts }

  tasks:
    - debug: msg="Node {{ hostname }} is type {{ device_os }} running software version {{ version }}"


