---
- name: manage NTP parameters on network devices
  hosts: "{{ devices | default('all') }}"
  gather_facts: no
  connection: local

  roles:
    - role: ntp
      state: present
      ntp_servers:
        - 1.1.1.1 
        - 2.2.2.2
        - 3.3.3.3
        - 4.4.4.4


